### ISSUE TITLE
Loading prop and state

### ISSUE THREAD

**Issue by zmnv** [tmmgn/react-native-backdrop#1]
Hello, Alexander.

What is for `loading` prop?
https://github.com/tmmgn/react-native-backdrop/blob/master/src/Backdrop.js#L47

Why do you set new variable `loading` in state which doesn't exist in constructor?
https://github.com/tmmgn/react-native-backdrop/blob/master/src/Backdrop.js#L99

**Comment by tmmgn** [comment]
Good day, sir. 
As i can see its some junk that i forgot to delete, PRs welcome, or if You dont want to do that, comment there and i will do this by self

**Comment by tmmgn** [comment]
Fixed
