### ISSUE TITLE
Top Backdrop

### ISSUE THREAD

**Issue by vadympetryshyn** [tmmgn/react-native-backdrop#10]
I need backdrop appear and disappear from the top of screen, how can I implement it?

**Comment by tmmgn** [comment]
unfortunately, its impossible with my package yet, you can fork it and do all the needed tweaks. I will try to implement this feature but not sure when i got enough time for that

**Comment by vadympetryshyn** [comment]
> unfortunately, its impossible with my package yet, you can fork it and do all the needed tweaks. I will try to implement this feature but not sure when i got enough time for that

Thanks, ok I will try to do it
