### ISSUE TITLE
[DOUBT] About ScrollView

### ISSUE THREAD

**Issue by Girum** [tmmgn/react-native-backdrop#12]
Hi!

I used the backdrop to insert a tabBar menu. When I use a component with a flatlist and various images, the scrolls works perfectly. But when I use a long text, and use ScrollView in it, the text dont Scroll. Anyone can help?

**Comment by tmmgn** [comment]
Hello friend, can you share your code so I can recreate this behavior?

**Comment by Girum** [comment]
Hi. For some reason, in a strange way, when I add a Touchable in the elements, I can scroll the view haha.
