### ISSUE TITLE
closedHeight and visible not working as expected

### ISSUE THREAD

**Issue by SimonBellucci** [tmmgn/react-native-backdrop#4]
Hello,

When `closedHeight` is provided, and `visible` is set to `false`, the Backdrop entirely disappear, wouldn't it be better for the Backdrop to swipe down to the provided `closedHeight` value ?

Maybe I am missing something in my code :

```
<Backdrop
     visible={visible}
     handleOpen={() => setVisible(true)}
     handleClose={() => setVisible(false)}
     onClose={() => {}}
     backdropStyle={{ backgroundColor: '#fff'}}
     closedHeight={350}
> .... </Backdrop>
```

**Comment by tmmgn** [comment]
You're right, there is something wrong with closedHeight, refactoring lib to react-native-reanimated ATM, will try to fix it there

**Comment by tmmgn** [comment]
In new version this is fixed to me, can you check this?
