### ISSUE TITLE
Scroll is not working in backdrops

### ISSUE THREAD

**Issue by madhudskumar** [tmmgn/react-native-backdrop#5]
ScrollView implementation as child is not working

**Comment by tmmgn** [comment]
Im doing huge refactor right now based on react-native-reanimated and scroll functionality will be there

**Comment by tmmgn** [comment]
Can you check new version, its not fully support for ScrollView, but now its behavior is much better

**Comment by IngDeiver** [comment]
This is very necesary, please fix.
