### ISSUE TITLE
Content appear from the bottom

### ISSUE THREAD

**Issue by vadympetryshyn** [tmmgn/react-native-backdrop#9]
I have the list of items in backdrop with "live content", backdrop is closed, and when I get new list items through the socket, backdrop appear from the bottom, because height of list is increasing at that moment. How can I prevent it?

**Comment by tmmgn** [comment]
interesting moment, will try to fix this asap

**Comment by tmmgn** [comment]
update release, feel free to test you issue with new version

**Comment by vadympetryshyn** [comment]
Now seems all is ok. Thanks!
